### ISSUE TITLE
"Unknown system error, please try again later."

### ISSUE THREAD

**Issue by splendidafk** [Trae-AI/Trae#1445]
yo devs at trae ai , fix this fucking shitty ass rookie error. holy shit dude. cant fucking use trae to code when this shitty error persists 24/7 dude. HOLY FUCK. 
no way you guys are so fucking lazy to fix such a small - pain in the ass issue. 
and clearly looking through forums and other repo issues , looks like im not the only one 
at this point fucking give me a compensation. i paid for and havent been able to use trae because of such a shit issue you guys cant fucking fix HOLY FUCK. anyway devs fix this shit , you are busting my balls along with other customers/users. 
( cancer from incompetent lazy dipshits who cant fix a simple fucking issue but care to butt-fuck aFuck ton of new features when i cant even use the fucking IDE because of the "Unknown system error, please try again later."
jesus christ cancer

<img width="959" height="60" alt="Image" src="https://github.com/user-attachments/assets/1a3138d3-1449-41af-aaf4-97276ed232e0" />

<img width="834" height="42" alt="Image" src="https://github.com/user-attachments/assets/13dc75bc-6266-4367-b38c-def1b47a497d" />

**Comment by Jessica-ppp** [comment]
You can try opening a new window, and this problem should be solved.

**Comment by splendidafk** [comment]
opening a new window doesnt do anything , neither does un-installing and re-installing , clearing cache , logging out and relogging in 
the issue still persists
